#ifndef GGP_COMPONENT_TYPES_H
#define GGP_COMPONENT_TYPES_H

enum CompType {
	MESH_RENDERER = 0,
	RIGID_BODY = 1,
	KINEMATIC_BODY = 2,
	INPUT_LISTENER = 3,
	DIRECTIONAL_LIGHT = 4,
	POINT_LIGHT = 5
};

#endif //GGP_COMPONENT_TYPES