#ifndef GGP_COMPONENT_TYPES_H
#define GGP_COMPONENT_TYPES_H

enum CompType {
	MATERIAL = 0,
	MESH_RENDERER = 1,
	RIGID_BODY = 2,
	KINEMATIC_BODY = 3,
	INPUT_LISTENER = 4
};

#endif //GGP_COMPONENT_TYPES