#ifndef GGP_GAME_OBJECT_TYPES_H
#define GGP_GAME_OBJECT_TYPES_H

enum GOType {
	GAME_OBJECT = 0,
	SCENE = 1,
	CAMERA = 3,
	DIR_LIGHT = 4,
	POINT_LIGHT = 5,
	SPOT_LIGHT = 6
};

#endif //GGP_GAME_OBJECT_TYPES_H